name: pages

on:
  push:
    branches:
      - main
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¤˜ checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ğŸ’ ruby
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '2.6'
      - name: ğŸ§ª jekyll
        run: |
          gem install jekyll bundler
          bundle install
      - name: ğŸ™ build
        run: bundle exec jekyll build
      - name: ğŸš€ deploy
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          pages_directory: _site
          commit_author: helloclarius
          commit_author_email: hello@clarius.org
          username: helloclarius
          password: ${{ secrets.ACCESS_TOKEN }}
          remote_url: https://github.com/clarius/stunts.git
          target_branch: main
